---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: generic
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" 
parameters:
  availability: nova
  type: quobyte
provisioner: kubernetes.io/cinder
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
parameters:
  availability: nova
  type: quobyte
provisioner: kubernetes.io/cinder
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: etcd-backup-gce-pd
provisioner: kubernetes.io/cinder 
parameters:
  type: quobyte
  availability: nova
